# Generated by Django 3.1.6 on 2021-09-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('wikipedia', models.URLField(blank=True, default='')),
                ('test', models.CharField(default='', max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('1', 'Aventure'), ('2', 'Thriller'), ('3', 'Fantastique'), ('4', 'Romance'), ('5', 'Horreur'), ('6', 'Science-fiction')], max_length=100)),
                ('tests', models.CharField(default='', max_length=2)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.author')),
            ],
        ),
    ]
