# Generated by Django 3.1.6 on 2021-09-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
